
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "q|-\x86'/\xe7R\xb7\xcb\xfc\xfd(\x93\x1e\xc7"
    
_lr_action_items = {'GT':([21,],[25,]),'RPAREN':([2,3,4,6,7,11,13,14,15,16,18,20,22,23,37,38,39,52,53,56,59,63,64,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,],[-27,-27,8,-2,-3,-27,18,19,-6,-27,-4,-7,37,-10,-8,-11,53,-9,-23,68,-27,77,78,80,81,-13,82,83,84,-27,-25,86,87,88,-12,-14,89,-20,-16,-19,-15,-24,-26,-22,-17,-18,-21,]),'SUB':([21,],[26,]),'LOADINST':([21,],[27,]),'ADD':([21,],[29,]),'REG':([24,25,26,27,28,29,30,31,32,33,34,36,40,41,43,44,47,48,50,51,54,55,57,58,59,61,62,65,72,],[39,40,41,42,43,44,45,46,47,48,49,51,54,55,57,58,61,62,64,65,66,67,69,70,72,75,76,79,72,]),'LT':([21,],[28,]),'NUM':([12,46,49,60,],[17,60,63,74,]),'CALL':([21,],[30,]),'BRANCH':([21,],[31,]),'LPAREN':([0,2,3,9,10,17,18,19,23,37,53,68,77,78,80,81,82,83,84,86,87,88,89,],[2,5,5,11,12,21,-4,-5,21,12,-23,-13,-12,-14,-20,-16,-19,-15,-24,-22,-17,-18,-21,]),'MUL':([21,],[32,]),'RETURN':([21,],[24,]),'DIV':([21,],[33,]),'CMP':([21,],[36,]),'LOADCONST':([21,],[34,]),'ID':([5,11,16,35,42,45,],[9,16,16,50,56,59,]),'STOREINST':([21,],[35,]),'$end':([1,8,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([2,3,],[3,3,]),'functions':([2,3,],[4,7,]),'blocks':([10,37,],[13,52,]),'reg_list':([59,72,],[71,85,]),'instruction':([17,23,],[23,23,]),'id_list':([11,16,],[14,20,]),'program':([0,],[1,]),'arguments':([9,],[10,]),'empty':([2,3,11,16,59,72,],[6,6,15,15,73,73,]),'instructions':([17,23,],[22,38,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> LPAREN functions RPAREN','program',3,'p_program','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',40),
  ('functions -> empty','functions',1,'p_functions','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',45),
  ('functions -> function functions','functions',2,'p_functions','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',46),
  ('function -> LPAREN ID arguments blocks RPAREN','function',5,'p_function','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',53),
  ('arguments -> LPAREN id_list RPAREN','arguments',3,'p_arguments','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',58),
  ('id_list -> empty','id_list',1,'p_id_list','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',63),
  ('id_list -> ID id_list','id_list',2,'p_id_list','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',64),
  ('blocks -> LPAREN NUM instructions RPAREN','blocks',4,'p_blocks','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',71),
  ('blocks -> LPAREN NUM instructions RPAREN blocks','blocks',5,'p_blocks','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',72),
  ('instructions -> instruction','instructions',1,'p_instructions','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',79),
  ('instructions -> instruction instructions','instructions',2,'p_instructions','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',80),
  ('instruction -> LPAREN LOADCONST REG NUM RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',87),
  ('instruction -> LPAREN LOADINST REG ID RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',88),
  ('instruction -> LPAREN STOREINST ID REG RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',89),
  ('instruction -> LPAREN ADD REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',90),
  ('instruction -> LPAREN SUB REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',91),
  ('instruction -> LPAREN MUL REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',92),
  ('instruction -> LPAREN DIV REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',93),
  ('instruction -> LPAREN LT REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',94),
  ('instruction -> LPAREN GT REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',95),
  ('instruction -> LPAREN CMP REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',96),
  ('instruction -> LPAREN BRANCH REG NUM NUM RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',97),
  ('instruction -> LPAREN RETURN REG RPAREN','instruction',4,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',98),
  ('instruction -> LPAREN CALL REG ID reg_list RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',99),
  ('reg_list -> empty','reg_list',1,'p_reg_list','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',104),
  ('reg_list -> REG reg_list','reg_list',2,'p_reg_list','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',105),
  ('empty -> <empty>','empty',0,'p_empty','/home/caitie/Documents/university/COMP3109_Paradigms/comp3109-interpreter/parser.py',110),
]
