
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc7mB\xf6E\x1a4F\x1a\x11\xb3{+\x9e}\xfd'
    
_lr_action_items = {'GT':([22,],[26,]),'RPAREN':([2,3,4,6,7,11,13,14,15,16,17,18,20,21,23,24,38,39,40,53,54,57,60,64,65,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,],[-28,-28,8,-2,-3,-28,18,19,-6,-28,21,-4,-7,-8,38,-11,-9,-12,54,-10,-24,69,-28,78,79,81,82,-14,83,84,85,-28,-26,87,88,89,-13,-15,90,-21,-17,-20,-16,-25,-27,-23,-18,-19,-22,]),'SUB':([22,],[27,]),'LOADINST':([22,],[28,]),'ADD':([22,],[30,]),'REG':([25,26,27,28,29,30,31,32,33,34,35,37,41,42,44,45,48,49,51,52,55,56,58,59,60,62,63,66,73,],[40,41,42,43,44,45,46,47,48,49,50,52,55,56,58,59,62,63,65,66,67,68,70,71,73,76,77,80,73,]),'LT':([22,],[29,]),'NUM':([12,47,50,61,],[17,61,64,75,]),'CALL':([22,],[31,]),'BRANCH':([22,],[32,]),'LPAREN':([0,2,3,9,10,17,18,19,24,38,54,69,78,79,81,82,83,84,85,87,88,89,90,],[2,5,5,11,12,22,-4,-5,22,12,-24,-14,-13,-15,-21,-17,-20,-16,-25,-23,-18,-19,-22,]),'MUL':([22,],[33,]),'RETURN':([22,],[25,]),'DIV':([22,],[34,]),'CMP':([22,],[37,]),'LOADCONST':([22,],[35,]),'ID':([5,11,16,36,43,46,],[9,16,16,51,57,60,]),'STOREINST':([22,],[36,]),'$end':([1,8,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([2,3,],[3,3,]),'functions':([2,3,],[4,7,]),'blocks':([10,38,],[13,53,]),'reg_list':([60,73,],[72,86,]),'instruction':([17,24,],[24,24,]),'id_list':([11,16,],[14,20,]),'program':([0,],[1,]),'arguments':([9,],[10,]),'empty':([2,3,11,16,60,73,],[6,6,15,15,74,74,]),'instructions':([17,24,],[23,39,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> LPAREN functions RPAREN','program',3,'p_program','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',40),
  ('functions -> empty','functions',1,'p_functions','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',45),
  ('functions -> function functions','functions',2,'p_functions','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',46),
  ('function -> LPAREN ID arguments blocks RPAREN','function',5,'p_function','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',53),
  ('arguments -> LPAREN id_list RPAREN','arguments',3,'p_arguments','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',58),
  ('id_list -> empty','id_list',1,'p_id_list','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',63),
  ('id_list -> ID id_list','id_list',2,'p_id_list','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',64),
  ('blocks -> LPAREN NUM RPAREN','blocks',3,'p_blocks','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',71),
  ('blocks -> LPAREN NUM instructions RPAREN','blocks',4,'p_blocks','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',72),
  ('blocks -> LPAREN NUM instructions RPAREN blocks','blocks',5,'p_blocks','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',73),
  ('instructions -> instruction','instructions',1,'p_instructions','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',86),
  ('instructions -> instruction instructions','instructions',2,'p_instructions','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',87),
  ('instruction -> LPAREN LOADCONST REG NUM RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',94),
  ('instruction -> LPAREN LOADINST REG ID RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',95),
  ('instruction -> LPAREN STOREINST ID REG RPAREN','instruction',5,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',96),
  ('instruction -> LPAREN ADD REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',97),
  ('instruction -> LPAREN SUB REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',98),
  ('instruction -> LPAREN MUL REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',99),
  ('instruction -> LPAREN DIV REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',100),
  ('instruction -> LPAREN LT REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',101),
  ('instruction -> LPAREN GT REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',102),
  ('instruction -> LPAREN CMP REG REG REG RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',103),
  ('instruction -> LPAREN BRANCH REG NUM NUM RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',104),
  ('instruction -> LPAREN RETURN REG RPAREN','instruction',4,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',105),
  ('instruction -> LPAREN CALL REG ID reg_list RPAREN','instruction',6,'p_instruction','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',106),
  ('reg_list -> empty','reg_list',1,'p_reg_list','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',111),
  ('reg_list -> REG reg_list','reg_list',2,'p_reg_list','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',112),
  ('empty -> <empty>','empty',0,'p_empty','/home/caitie/Documents/university/COMP3109_Paradigms/assignment2/interpreter/parser.py',117),
]
